FROM ubuntu:18.04
maintainer yancy ribbens "yribbens@credly.com"

RUN apt-get update -qq && apt-get install -y git wget build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils python3 libboost-all-dev libminiupnpc-dev libzmq3-dev python3-pip locales vim python3.6 python3.6-dev uwsgi uwsgi-src uuid-dev libcap-dev libpcre3-dev python-pip python-dev nginx netcat

# default to UTF8 character set
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LC_TYPE en_US.UTF-8
RUN locale-gen en_US.UTF-8

# configure cert-issuer
COPY . /cert-issuer
COPY conf_testnet.ini /etc/cert-issuer/conf.ini
RUN mkdir -p /etc/cert-issuer/
WORKDIR /cert-issuer
RUN pip3 install --upgrade pip \
    && pip3 install .


# configure wsgi
ENV PYTHON python3.6
WORKDIR /root
RUN uwsgi --build-plugin "/usr/src/uwsgi/plugins/python python36"
RUN cp /root/python36_plugin.so /cert-issuer
RUN chmod 644 /cert-issuer/python36_plugin.so
RUN pip3 install uwsgi flask

# configure nginx
ARG SERVER=127.0.0.1
EXPOSE 80
WORKDIR /cert-issuer
COPY cert_issuer_site /etc/nginx/sites-available
RUN ln -s /etc/nginx/sites-available/cert_issuer_site /etc/nginx/sites-enabled
RUN sed -i.bak "s/<server-name>/$SERVER/g" /etc/nginx/sites-available/cert_issuer_site
RUN sed -i.bak "s/# server_names_hash_bucket_size 64/server_names_hash_bucket_size 128/g" /etc/nginx/nginx.conf
RUN chmod +x start-cert-issuer.sh


ENTRYPOINT ./start-cert-issuer.sh && service nginx start && uwsgi --ini wsgi.ini
